title: Hutscape
description: Everyday practical home automation projects
url: "https://hutscape.com"
markdown: kramdown
permalink: /:title
youtube: https://www.youtube.com/user/sweska/videos
github:
  repository_url: https://github.com/hutscape/hutscape.github.io
exclude: [
  _tutorials/.embuild/*,
  _tutorials/*.h,
  _tutorials/*.ino,
  _tutorials/*.json,
  _tutorials/*Makefile,
  _tutorials/*.cpp,
  _tutorials/*.c,
  _tutorials/*.cmake,
  _tutorials/*.sal,
  _tutorials/*.py,
  _tutorials/*sdkconfig*,
  _tutorials/main/*,
  _tutorials/src/*,
  _tutorials/sdkconfig*,
  _tutorials/*Dockerfile*,
  _tutorials/CMake*,
  _tutorials/**/build/*,
  _tutorials/**/blink/*,
  _tutorials/*README*,
  _tutorials/*.ini,
  _tutorials/*.txt,
  _tutorials/*.mk,
  _tutorials/*.yaml,
  _tutorials/*.pio,
  _tutorials/*.cargo*,
  _tutorials/*target*,
  _tutorials/*.rs,
  _tutorials/*.toml,
  _tutorials/*.lock,
  _tutorials/*.bin,
  CNAME,
  Gemfile,
  Gemfile.lock,
  LICENSE.md,
  Makefile,
  README.md
]
collections:
  tutorials:
    output: true
    permalink: /tutorials/:name
  checklists:
    output: true
    permalink: /checklists/:name
  tools:
    output: true
    permalink: /tools/:name
