esphome:
  name: blinky

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: arduino
    version: 2.0.3
    platform_version: 5.1.0

logger:
  level: VERBOSE
  baud_rate: 115200
  deassert_rts_dtr: true
  # Enable USB CDC: https://esphome.io/components/logger.html#hardware-uarts
  # hardware_uart: USB_CDC

switch:
  - platform: gpio
    pin:
      number: 5
      mode: output
    id: led

interval:
  - interval: 2s
    then:
      - switch.toggle: led
      - logger.log: "LED toggling"
