esphome:
  name: hello

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: arduino
    version: 2.0.4
    platform_version: 5.1.0

logger:
  level: DEBUG
  baud_rate: 0
  deassert_rts_dtr: true
